'use strict';

/**
 * BodyBank — the EDITABLE progress-report document.
 *
 * The blood-comparison PDF used to be rendered straight off `comparison_data` +
 * `ai_verdict`. That made it un-editable: whatever Claude wrote is what the client
 * received. This module introduces a middle layer — a plain-JSON **document** that
 * describes the report as an ordered list of renderable sections.
 *
 *   raw comparison + AI verdict  ──buildComparisonDoc()──▶  doc  ──PDFKit──▶  PDF
 *                                                           ▲
 *                                             doctor edits it in the app
 *
 * The doc is the single source of truth for rendering, so "what the doctor sees in
 * the editor" and "what prints" cannot drift. When a comparison has never been
 * edited we build the default doc on the fly; once it has, the stored doc wins.
 *
 * Section types (all share id/type/show/pageBreak/title/subtitle):
 *   trend      — the marker-per-test-date table
 *   text       — heading + optional badge + prose
 *   cards      — grouped "what changed" cards (improvements / concerns / watch)
 *   table      — generic column+row table (recommendations, supplements, retests)
 *   callout    — a boxed highlight (bottom line, coach's note)
 *   disclaimer — the medical disclaimer block
 *
 * Every section can be hidden, retitled, reordered, or deleted, and new text /
 * table / cards / callout sections can be added anywhere. That is what gives the
 * reviewing doctor full control over the final printout.
 */

const DOC_VERSION = 1;

// Guard rails for anything arriving from the browser. Generous enough that no real
// report hits them, tight enough that a malformed payload can't blow up the PDF.
const LIMITS = {
  sections: 80,
  title: 240,
  body: 40000,
  short: 600,
  tableColumns: 10,
  tableRows: 400,
  cardGroups: 16,
  cardItems: 200,
  trendPanels: 60,
  trendMarkers: 300,
  trendColumns: 12,
  statItems: 8
};

const CARD_TONES = ['good', 'bad', 'watch'];
const CALLOUT_TONES = ['green', 'gold', 'amber', 'red', 'blue'];
const COLUMN_STYLES = ['normal', 'strong', 'muted', 'accent', 'warn', 'action'];
const TREND_DIRS = ['improving', 'worsening', 'stable', 'changed', 'na'];
const SECTION_TYPES = ['trend', 'text', 'cards', 'table', 'callout', 'disclaimer'];

const DEFAULT_DISCLAIMER =
  'This progress report is generated by BodyBank.fit’s AI Health System from your own previous blood analyses. ' +
  'It does not constitute a medical diagnosis. All supplement and dietary recommendations must be reviewed with your ' +
  'physician before implementation.';

const DEFAULT_COVER_FOOTNOTE =
  'This progress report compares your own previous BodyBank blood analyses. It is for informational purposes only and ' +
  'does not constitute a medical diagnosis. Please review it with your physician.';

// --------------------------------------------------------------------------
// small helpers
// --------------------------------------------------------------------------

let idSeq = 0;
/** Stable-enough unique id for a section/row/item created at build or edit time. */
function newId(prefix) {
  idSeq += 1;
  return `${prefix || 'x'}-${Date.now().toString(36)}-${idSeq.toString(36)}`;
}

function str(v, max) {
  if (v == null) return '';
  const s = typeof v === 'string' ? v : String(v);
  const cap = max || LIMITS.short;
  return s.length > cap ? s.slice(0, cap) : s;
}

function bool(v, dflt) {
  if (v === true) return true;
  if (v === false) return false;
  return !!dflt;
}

function arr(v, max) {
  if (!Array.isArray(v)) return [];
  return max && v.length > max ? v.slice(0, max) : v;
}

function pick(v, allowed, dflt) {
  const s = String(v == null ? '' : v);
  return allowed.indexOf(s) >= 0 ? s : dflt;
}

function num(v, dflt) {
  const n = Number(v);
  return Number.isFinite(n) ? n : dflt;
}

const MONTHS_LONG = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December'];
const MONTHS_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

/**
 * Parse a report date without letting a timezone drag it onto the previous day.
 * A pg DATE arrives as 'YYYY-MM-DD'; treating that as UTC midnight and then reading
 * local components shifts it back a day west of Greenwich.
 */
function toLocalDate(v) {
  if (v instanceof Date) return Number.isNaN(v.getTime()) ? null : v;
  const s = String(v == null ? '' : v);
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
  if (m) return new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  const d = new Date(s);
  return Number.isNaN(d.getTime()) ? null : d;
}

function formatLongDate(v) {
  const d = toLocalDate(v) || new Date();
  return `${d.getDate()} ${MONTHS_LONG[d.getMonth()]} ${d.getFullYear()}`;
}

function formatShortDate(v) {
  const d = toLocalDate(v);
  if (!d) return String(v || '—');
  return `${String(d.getDate()).padStart(2, '0')} ${MONTHS_SHORT[d.getMonth()]} ${String(d.getFullYear()).slice(2)}`;
}

function nonEmptyArray(v) { return Array.isArray(v) && v.length > 0; }

function trendArrow(delta) {
  if (delta == null || Math.abs(delta) <= 1e-9) return 'flat';
  return delta > 0 ? 'up' : 'down';
}

function trendLabel(marker) {
  if (marker.deltaPct != null) return `${marker.delta > 0 ? '+' : ''}${marker.deltaPct}%`;
  if (marker.delta != null) return `${marker.delta > 0 ? '+' : ''}${marker.delta}`;
  return '';
}

// --------------------------------------------------------------------------
// default document builder
// --------------------------------------------------------------------------

/**
 * Build the default (un-edited) document for a comparison.
 *
 * @param {object} input
 * @param {object} input.comparison aligned matrix from bloodComparisonService.alignReports
 * @param {object} input.verdict    Claude longitudinal verdict (may be null/{})
 * @param {string} input.adminNotes coach note stored on the comparison row
 * @param {object} input.user       { name, age, gender, goal }
 * @param {*}      [input.reportDate] date shown on the cover (defaults to today)
 * @returns {object} document
 */
function buildComparisonDoc(input) {
  const comparison = (input && input.comparison) || {};
  const verdict = (input && input.verdict) || {};
  const user = (input && input.user) || {};
  const adminNotes = str((input && input.adminNotes) || '', LIMITS.body);
  const reports = Array.isArray(comparison.reports) ? comparison.reports : [];
  const panels = Array.isArray(comparison.panels) ? comparison.panels : [];
  const n = reports.length;

  const span = n >= 2
    ? `${formatShortDate(reports[0].date)}  →  ${formatShortDate(reports[n - 1].date)}`
    : (n === 1 ? formatShortDate(reports[0].date) : '—');

  const cover = {
    show: true,
    brandTitle: 'Blood Report Progress Review',
    brandSubtitle: `Longitudinal comparison across ${n} test${n === 1 ? '' : 's'}`,
    showFields: true,
    fields: {
      patientName: str(user.name || 'Member', LIMITS.short),
      reportDate: formatLongDate(input && input.reportDate ? input.reportDate : new Date()),
      reportType: 'Progress Review',
      ageGender: `${user.age || '—'} / ${user.gender || '—'}`,
      goal: str(user.goal || '—', LIMITS.short),
      testsCompared: span
    },
    trajectory: {
      show: true,
      label: str(verdict.overall_trajectory || 'Mixed', 80),
      summary: str(
        verdict.executive_summary ||
        'The trajectory of your key blood markers across these tests is summarised on the following pages.',
        LIMITS.body
      )
    },
    stats: {
      show: true,
      items: [
        { id: 'stat-improved', label: 'IMPROVING', value: comparison.improvedCount != null ? String(comparison.improvedCount) : '', tone: 'green', show: comparison.improvedCount != null },
        { id: 'stat-worsened', label: 'WORSENING', value: comparison.worsenedCount != null ? String(comparison.worsenedCount) : '', tone: 'red', show: comparison.worsenedCount != null },
        { id: 'stat-markers', label: 'MARKERS TRACKED', value: comparison.markerCount != null ? String(comparison.markerCount) : '', tone: 'blue', show: comparison.markerCount != null }
      ]
    },
    footnote: { show: true, text: DEFAULT_COVER_FOOTNOTE }
  };

  const sections = [];

  // ---- 1. marker trend table ------------------------------------------------
  // Every marker is carried into the doc, but only the ones that moved or were
  // flagged start out visible — matching the old print behaviour while letting the
  // doctor switch a quiet marker back on.
  const trendPanels = panels.map((p, pi) => {
    const markers = (p.markers || []).map((m, mi) => ({
      id: `mk-${pi}-${mi}`,
      show: !!(m.changed || m.anyAbnormal),
      name: str(m.display || '', LIMITS.short),
      unit: str(m.unit || '', 40),
      reference: str(m.referenceRange || '', LIMITS.short),
      values: reports.map((r, ci) => {
        const cell = (m.cells || [])[ci];
        return {
          text: cell && cell.present ? str(cell.value || '', 80) : '',
          status: cell && cell.present ? str(cell.status || '', 40) : ''
        };
      }),
      trend: {
        text: trendLabel(m),
        dir: pick(m.direction, TREND_DIRS, 'na'),
        arrow: trendArrow(m.delta)
      }
    }));
    return {
      id: `pn-${pi}`,
      name: str(p.name || 'Panel', LIMITS.short),
      show: markers.some((m) => m.show),
      markers
    };
  });

  sections.push({
    id: 'sec-trend',
    type: 'trend',
    show: trendPanels.some((p) => p.show),
    pageBreak: true,
    title: 'Marker Trend — value at each test',
    subtitle: '',
    intro: 'Only markers that moved or were flagged are shown. The trend column reflects movement relative to the ' +
      'reference range (green = moving into range, red = moving away).',
    columns: reports.map((r) => ({
      id: String(r.id),
      label: formatShortDate(r.date),
      show: true
    })),
    panels: trendPanels
  });

  // ---- 2. clinical trajectory ----------------------------------------------
  const narrativeBody = str(verdict.trajectory_narrative || verdict.executive_summary || '', LIMITS.body);
  sections.push({
    id: 'sec-narrative',
    type: 'text',
    show: !!narrativeBody,
    pageBreak: true,
    title: 'Clinical Trajectory',
    subtitle: '',
    badge: {
      show: !!verdict.trajectory_score_delta,
      label: 'MOVEMENT',
      text: str(verdict.trajectory_score_delta || '', LIMITS.short)
    },
    align: 'justify',
    body: narrativeBody
  });

  // ---- 3. what changed ------------------------------------------------------
  const changeGroups = [
    { id: 'grp-improvements', title: 'Improvements', tone: 'good', src: verdict.improvements },
    { id: 'grp-concerns', title: 'Concerns', tone: 'bad', src: verdict.concerns },
    { id: 'grp-watch', title: 'Still to Watch', tone: 'watch', src: verdict.unchanged_watch }
  ].map((g) => ({
    id: g.id,
    title: g.title,
    tone: g.tone,
    show: nonEmptyArray(g.src),
    items: arr(g.src, LIMITS.cardItems).map((it, i) => ({
      id: `${g.id}-${i}`,
      show: true,
      marker: str((it && it.marker) || '', LIMITS.short),
      from: str(it && it.from != null ? it.from : '', LIMITS.short),
      to: str(it && (it.to != null ? it.to : (it.value != null ? it.value : '')), LIMITS.short),
      level: pick(it && it.level, ['High', 'Medium', 'Low'], ''),
      meaning: str((it && (it.meaning || it.note)) || '', LIMITS.body)
    }))
  }));

  sections.push({
    id: 'sec-changes',
    type: 'cards',
    show: changeGroups.some((g) => g.show && g.items.length),
    pageBreak: true,
    title: 'What Changed',
    subtitle: '',
    groups: changeGroups
  });

  // ---- 4. what to do now (intro + two tables) -------------------------------
  const interventions = str(verdict.interventions_assessment || '', LIMITS.body);
  sections.push({
    id: 'sec-actions-intro',
    type: 'text',
    show: !!interventions || nonEmptyArray(verdict.updated_recommendations) || nonEmptyArray(verdict.updated_supplements),
    pageBreak: true,
    title: 'What To Do Now',
    subtitle: '',
    badge: { show: false, label: '', text: '' },
    align: 'justify',
    body: interventions
  });

  sections.push(buildTable({
    id: 'sec-recommendations',
    subtitle: 'Updated Recommendations',
    show: nonEmptyArray(verdict.updated_recommendations),
    pageBreak: false,
    columns: [
      { id: 'area', header: 'Area', width: 0.2, style: 'accent' },
      { id: 'action', header: 'Action', width: 0.42, style: 'normal' },
      { id: 'reason', header: 'Why', width: 0.38, style: 'muted' }
    ],
    rows: arr(verdict.updated_recommendations, LIMITS.tableRows).map((r) => ({
      area: (r && r.area) || '', action: (r && r.action) || '', reason: (r && r.reason) || ''
    }))
  }));

  sections.push(buildTable({
    id: 'sec-supplements',
    subtitle: 'Supplement Plan',
    show: nonEmptyArray(verdict.updated_supplements),
    pageBreak: false,
    columns: [
      { id: 'name', header: 'Supplement', width: 0.26, style: 'accent' },
      { id: 'action', header: 'Action', width: 0.16, style: 'action' },
      { id: 'dose', header: 'Dose', width: 0.2, style: 'muted' },
      { id: 'reason', header: 'Reason', width: 0.38, style: 'muted' }
    ],
    rows: arr(verdict.updated_supplements, LIMITS.tableRows).map((s) => ({
      name: (s && s.name) || '', action: (s && s.action) || '', dose: (s && s.dose) || '', reason: (s && s.reason) || ''
    }))
  }));

  // ---- 5. next steps --------------------------------------------------------
  sections.push(buildTable({
    id: 'sec-retest',
    title: 'Next Steps',
    subtitle: 'Recommended Retesting',
    show: nonEmptyArray(verdict.next_retest),
    pageBreak: true,
    columns: [
      { id: 'test', header: 'Test', width: 0.36, style: 'strong' },
      { id: 'when', header: 'When', width: 0.2, style: 'warn' },
      { id: 'reason', header: 'Reason', width: 0.44, style: 'muted' }
    ],
    rows: arr(verdict.next_retest, LIMITS.tableRows).map((r) => ({
      test: (r && r.test) || '', when: (r && r.when) || '', reason: (r && r.reason) || ''
    }))
  }));

  sections.push({
    id: 'sec-bottom-line',
    type: 'callout',
    show: !!verdict.final_verdict,
    pageBreak: false,
    title: '',
    subtitle: '',
    label: 'BOTTOM LINE',
    tone: 'green',
    italic: false,
    text: str(verdict.final_verdict || '', LIMITS.body)
  });

  sections.push({
    id: 'sec-coach-note',
    type: 'callout',
    show: !!adminNotes,
    pageBreak: false,
    title: '',
    subtitle: 'A Note From Your Coach',
    label: '',
    tone: 'gold',
    italic: true,
    text: adminNotes
  });

  sections.push({
    id: 'sec-disclaimer',
    type: 'disclaimer',
    show: true,
    pageBreak: false,
    title: '',
    subtitle: '',
    label: 'Medical Disclaimer: ',
    text: DEFAULT_DISCLAIMER
  });

  return { version: DOC_VERSION, cover, sections };
}

/** Assemble a `table` section from a compact spec (columns + plain-object rows). */
function buildTable(spec) {
  const columns = (spec.columns || []).map((c) => ({
    id: c.id,
    header: str(c.header || '', LIMITS.title),
    width: num(c.width, 0.25),
    style: pick(c.style, COLUMN_STYLES, 'normal'),
    show: true
  }));
  const rows = (spec.rows || []).map((r, i) => {
    const cells = {};
    columns.forEach((c) => { cells[c.id] = str(r[c.id] || '', LIMITS.body); });
    return { id: `${spec.id}-r${i}`, show: true, cells };
  });
  return {
    id: spec.id,
    type: 'table',
    show: !!spec.show,
    pageBreak: !!spec.pageBreak,
    title: str(spec.title || '', LIMITS.title),
    subtitle: str(spec.subtitle || '', LIMITS.title),
    columns,
    rows
  };
}

// --------------------------------------------------------------------------
// sanitisation of an edited document coming back from the browser
// --------------------------------------------------------------------------

/**
 * Coerce an untrusted document into the exact shape the renderer expects.
 * Unknown keys are dropped, strings are capped, arrays are bounded. Never throws —
 * a hopeless payload degrades to an empty (but valid) document, and the caller
 * decides whether to reject it.
 *
 * @param {*} input raw parsed JSON from the client
 * @returns {object} a valid document
 */
function sanitizeComparisonDoc(input) {
  const src = (input && typeof input === 'object' && !Array.isArray(input)) ? input : {};
  return {
    version: DOC_VERSION,
    cover: sanitizeCover(src.cover),
    sections: arr(src.sections, LIMITS.sections)
      .map(sanitizeSection)
      .filter(Boolean)
  };
}

function sanitizeCover(c) {
  const src = (c && typeof c === 'object') ? c : {};
  const f = (src.fields && typeof src.fields === 'object') ? src.fields : {};
  const t = (src.trajectory && typeof src.trajectory === 'object') ? src.trajectory : {};
  const s = (src.stats && typeof src.stats === 'object') ? src.stats : {};
  const fn = (src.footnote && typeof src.footnote === 'object') ? src.footnote : {};
  return {
    show: bool(src.show, true),
    brandTitle: str(src.brandTitle || 'Blood Report Progress Review', LIMITS.title),
    brandSubtitle: str(src.brandSubtitle || '', LIMITS.title),
    showFields: bool(src.showFields, true),
    fields: {
      patientName: str(f.patientName || '', LIMITS.short),
      reportDate: str(f.reportDate || '', LIMITS.short),
      reportType: str(f.reportType || '', LIMITS.short),
      ageGender: str(f.ageGender || '', LIMITS.short),
      goal: str(f.goal || '', LIMITS.short),
      testsCompared: str(f.testsCompared || '', LIMITS.short)
    },
    trajectory: {
      show: bool(t.show, true),
      label: str(t.label || '', 80),
      summary: str(t.summary || '', LIMITS.body)
    },
    stats: {
      show: bool(s.show, true),
      items: arr(s.items, LIMITS.statItems).map((it, i) => ({
        id: str((it && it.id) || `stat-${i}`, 80),
        label: str((it && it.label) || '', 80),
        value: str((it && it.value) || '', 40),
        tone: pick(it && it.tone, ['green', 'red', 'blue', 'amber', 'gold'], 'blue'),
        show: bool(it && it.show, true)
      }))
    },
    footnote: {
      show: bool(fn.show, true),
      text: str(fn.text || '', LIMITS.body)
    }
  };
}

function sanitizeSectionBase(s, i) {
  return {
    id: str((s && s.id) || newId(`sec-${i}`), 80),
    type: pick(s && s.type, SECTION_TYPES, 'text'),
    show: bool(s && s.show, true),
    pageBreak: bool(s && s.pageBreak, false),
    title: str((s && s.title) || '', LIMITS.title),
    subtitle: str((s && s.subtitle) || '', LIMITS.title)
  };
}

function sanitizeSection(s, i) {
  if (!s || typeof s !== 'object') return null;
  const base = sanitizeSectionBase(s, i);
  if (base.type === 'trend') {
    return Object.assign(base, {
      intro: str(s.intro || '', LIMITS.body),
      columns: arr(s.columns, LIMITS.trendColumns).map((c, ci) => ({
        id: str((c && c.id) || `col-${ci}`, 80),
        label: str((c && c.label) || '', 80),
        show: bool(c && c.show, true)
      })),
      panels: arr(s.panels, LIMITS.trendPanels).map((p, pi) => ({
        id: str((p && p.id) || `pn-${pi}`, 80),
        name: str((p && p.name) || '', LIMITS.short),
        show: bool(p && p.show, true),
        markers: arr(p && p.markers, LIMITS.trendMarkers).map((m, mi) => ({
          id: str((m && m.id) || `mk-${pi}-${mi}`, 80),
          show: bool(m && m.show, true),
          name: str((m && m.name) || '', LIMITS.short),
          unit: str((m && m.unit) || '', 40),
          reference: str((m && m.reference) || '', LIMITS.short),
          values: arr(m && m.values, LIMITS.trendColumns).map((v) => ({
            text: str((v && v.text) || '', 80),
            status: str((v && v.status) || '', 40)
          })),
          trend: {
            text: str((m && m.trend && m.trend.text) || '', 40),
            dir: pick(m && m.trend && m.trend.dir, TREND_DIRS, 'na'),
            arrow: pick(m && m.trend && m.trend.arrow, ['up', 'down', 'flat'], 'flat')
          }
        }))
      }))
    });
  }
  if (base.type === 'text') {
    const b = (s.badge && typeof s.badge === 'object') ? s.badge : {};
    return Object.assign(base, {
      badge: { show: bool(b.show, false), label: str(b.label || '', 60), text: str(b.text || '', LIMITS.short) },
      align: pick(s.align, ['justify', 'left'], 'justify'),
      body: str(s.body || '', LIMITS.body)
    });
  }
  if (base.type === 'cards') {
    return Object.assign(base, {
      groups: arr(s.groups, LIMITS.cardGroups).map((g, gi) => ({
        id: str((g && g.id) || `grp-${gi}`, 80),
        title: str((g && g.title) || '', LIMITS.title),
        tone: pick(g && g.tone, CARD_TONES, 'good'),
        show: bool(g && g.show, true),
        items: arr(g && g.items, LIMITS.cardItems).map((it, ii) => ({
          id: str((it && it.id) || `${gi}-${ii}`, 80),
          show: bool(it && it.show, true),
          marker: str((it && it.marker) || '', LIMITS.short),
          from: str((it && it.from) || '', LIMITS.short),
          to: str((it && it.to) || '', LIMITS.short),
          level: pick(it && it.level, ['High', 'Medium', 'Low'], ''),
          meaning: str((it && it.meaning) || '', LIMITS.body)
        }))
      }))
    });
  }
  if (base.type === 'table') {
    const columns = arr(s.columns, LIMITS.tableColumns).map((c, ci) => ({
      id: str((c && c.id) || `c${ci}`, 80),
      header: str((c && c.header) || '', LIMITS.title),
      width: Math.min(1, Math.max(0.04, num(c && c.width, 0.25))),
      style: pick(c && c.style, COLUMN_STYLES, 'normal'),
      show: bool(c && c.show, true)
    }));
    return Object.assign(base, {
      columns,
      rows: arr(s.rows, LIMITS.tableRows).map((r, ri) => {
        const cells = {};
        const srcCells = (r && r.cells && typeof r.cells === 'object') ? r.cells : {};
        columns.forEach((c) => { cells[c.id] = str(srcCells[c.id] || '', LIMITS.body); });
        return { id: str((r && r.id) || `r${ri}`, 80), show: bool(r && r.show, true), cells };
      })
    });
  }
  if (base.type === 'callout') {
    return Object.assign(base, {
      label: str(s.label || '', 60),
      tone: pick(s.tone, CALLOUT_TONES, 'green'),
      italic: bool(s.italic, false),
      text: str(s.text || '', LIMITS.body)
    });
  }
  // disclaimer
  return Object.assign(base, {
    label: str(s.label || 'Medical Disclaimer: ', 60),
    text: str(s.text || DEFAULT_DISCLAIMER, LIMITS.body)
  });
}

// --------------------------------------------------------------------------
// small queries over a document
// --------------------------------------------------------------------------

/** True when the document would print at least one visible section. */
function docHasVisibleContent(doc) {
  if (!doc) return false;
  if (doc.cover && doc.cover.show !== false) return true;
  return (doc.sections || []).some((s) => s && s.show !== false);
}

/** The coach-note text held in the document, so `admin_notes` can stay in sync. */
function docCoachNote(doc) {
  const s = ((doc && doc.sections) || []).filter((x) => x && x.id === 'sec-coach-note')[0];
  return s && s.show !== false ? String(s.text || '') : '';
}

/**
 * Return a copy of the document with the coach note replaced (used when a note is
 * saved from outside the editor). Pure: the caller's document is left untouched, so
 * a failure mid-update cannot leave a half-edited object behind.
 */
function setDocCoachNote(input, note) {
  if (!input || !Array.isArray(input.sections)) return input;
  const doc = { ...input, sections: input.sections.map((s) => ({ ...s })) };
  const text = String(note == null ? '' : note);
  const existing = doc.sections.filter((x) => x && x.id === 'sec-coach-note')[0];
  if (existing) {
    existing.text = text;
    existing.show = !!text;
    return doc;
  }
  const disclaimerAt = doc.sections.findIndex((x) => x && x.type === 'disclaimer');
  const section = {
    id: 'sec-coach-note',
    type: 'callout',
    show: !!text,
    pageBreak: false,
    title: '',
    subtitle: 'A Note From Your Coach',
    label: '',
    tone: 'gold',
    italic: true,
    text
  };
  if (disclaimerAt >= 0) doc.sections.splice(disclaimerAt, 0, section);
  else doc.sections.push(section);
  return doc;
}

module.exports = {
  DOC_VERSION,
  LIMITS,
  DEFAULT_DISCLAIMER,
  buildComparisonDoc,
  sanitizeComparisonDoc,
  docHasVisibleContent,
  docCoachNote,
  setDocCoachNote,
  // shared formatting so the PDF and the editor agree on dates
  formatLongDate,
  formatShortDate,
  newId
};
